# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPzc4TV55HVbvF_AQ0h_t5xnGtY_jY_k
"""

!pip install streamlit -q
!npm install -g localtunnel
!pip install streamlit pyngrok xgboost pandas numpy scikit-learn -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import pandas as pd
# import numpy as np
# 
# # Page Configuration
# st.set_page_config(page_title="Demand Forecasting App", layout="centered")
# 
# @st.cache_resource
# def load_artifacts():
#     with open("XG_Boost_demand_model.pickle", "rb") as f:
#         model = pickle.load(f)
#     with open("label_encoders.pickle", "rb") as f:
#         encoders = pickle.load(f)
#     return model, encoders
# 
# # Load model and encoders
# model, label_encoders = load_artifacts()
# 
# st.title("Demand Forecasting App")
# st.write("Predict future product demand based on pricing, promotion, and inventory parameters.")
# st.divider()
# 
# # Inputs
# col1, col2 = st.columns(2)
# 
# with col1:
#     price = st.number_input("Price ($)", min_value=0.0, value=50.0, step=1.0)
#     discount = st.number_input("Discount (%)", min_value=0, max_value=100, value=10)
#     inventory_level = st.number_input("Inventory Level", min_value=0, value=100, step=10)
# 
# with col2:
#     promotion = st.selectbox("Promotion Active", options=[0, 1], format_func=lambda x: "Yes" if x == 1 else "No")
#     competitor_pricing = st.number_input("Competitor Pricing ($)", min_value=0.0, value=50.0, step=1.0)
# 
#     category_list = label_encoders["category"].classes_.tolist() if "category" in label_encoders else ["Electronics", "Clothing", "Grocery", "Toys", "Furniture"]
#     category = st.selectbox("Category", category_list)
# 
# # Dataframe matching the training features exact schema
# input_df = pd.DataFrame({
#     "Price": [price],
#     "Discount": [discount],
#     "Inventory Level": [inventory_level],
#     "Promotion": [promotion],
#     "Competitor Pricing": [competitor_pricing],
#     "Category": [category]
# })
# 
# # Transform categorical variables using loaded encoder
# if "category" in label_encoders:
#     input_df["Category"] = label_encoders["category"].transform(input_df["Category"])
# 
# st.divider()
# 
# if st.button("Predict Demand", type="primary"):
#     prediction = model.predict(input_df)
#     predicted_units = max(0, int(np.round(prediction[0])))
#     st.success(f"Predicted Demand: **{predicted_units} units**")

from pyngrok import ngrok

# Set your ngrok authtoken
NGROK_AUTH_TOKEN = "3HppX66gy39cbt8breeJ8lcuINR_7n92FBptUZu4mn7z9d4Vb"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Establish public tunnel
public_url = ngrok.connect(8501)
print(f"Click link to view Streamlit App: {public_url}")

# Launch app inside Colab environment
!streamlit run app.py